package com.blueprintit.dbom;

/**
 * @author Dave
 * 
 * A field represents a property of a particular table. A field my be held in a database or it
 * may be some dynamic property generated by a plugin.
 */
public class Field
{
	private Table table;
	
	public String getName()
	{
		return null;
	}
	
	public Table getTable()
	{
		return table;
	}
}
