package com.blueprintit.dbom;

import javax.servlet.ServletRequest;

/**
 * @author Dave
 * 
 * A field represents a property of a particular table. A field my be held in a database or it
 * may be some dynamic property generated by a plugin.
 */
public interface Field
{
	public String getName();
	
	public Table getTable();
	
	public Object getValue(TableRecord record, ServletRequest request);
}
